source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.2'
gem 'jekyll-scholar'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-archives'
gem 'jekyll-avatar'
gem 'jekyll-include-cache'
